### ISSUE TITLE
Getting a 401 error from the internal server after clicking 'authorize' on Strava

### ISSUE THREAD

**Issue by meltie** [barrald/strava-uploader#1]
Hello!

I'm getting an error after clicking 'authorize'.

I enabled debugging by inserting "app.debug = True" on line 21, and got this:

```
python strava_local_client.py get_write_ten 8c3d2fafb8b857d699e7411a2ff8d7a3c4364b38 e8a0d4153cdc683e90322818d938cc9df5ee79bc
On OS X - launching https://www.strava.com/oauth/authorize?state=from_cli&redirect_uri=http%3A%2F%2F127.0.0.1%3A8000%2Fauth&response_type=code&client_id=8c3d2fafb8b857d699e7411a2ff8d7a3c4364b38&scope=view_private%2Cwrite&approval_prompt=auto at default browser
 * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
 * Restarting with stat
On OS X - launching https://www.strava.com/oauth/authorize?state=from_cli&redirect_uri=http%3A%2F%2F127.0.0.1%3A8000%2Fauth&response_type=code&client_id=8c3d2fafb8b857d699e7411a2ff8d7a3c4364b38&scope=view_private%2Cwrite&approval_prompt=auto at default browser
 * Debugger is active!
 * Debugger pin code: 236-568-594
127.0.0.1 - - [20/Aug/2016 19:54:26] "GET /auth?state=from_cli&code=cfec5c3b0e6404d12fe7d616c0934c32446b5ea9 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/melt/strava-uploader/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/melt/strava-uploader/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/melt/strava-uploader/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/melt/strava-uploader/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/melt/strava-uploader/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/melt/strava-uploader/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/melt/strava-uploader/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/melt/strava-uploader/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/melt/strava-uploader/strava_local_client.py", line 35, in auth_callback
    code=code
  File "/Users/melt/strava-uploader/venv/lib/python2.7/site-packages/stravalib/client.py", line 134, in exchange_code_for_token
    code=code)
  File "/Users/melt/strava-uploader/venv/lib/python2.7/site-packages/stravalib/protocol.py", line 106, in exchange_code_for_token
    method='POST')
  File "/Users/melt/strava-uploader/venv/lib/python2.7/site-packages/stravalib/protocol.py", line 137, in _request
    self._handle_protocol_error(raw)
  File "/Users/melt/strava-uploader/venv/lib/python2.7/site-packages/stravalib/protocol.py", line 182, in _handle_protocol_error
    raise x
HTTPError: 401 Client Error: Unauthorized [Authorization Error: [{u'field': u'', u'code': u'invalid', u'resource': u'Application'}]]
```

I am running on Mac OSX, using virtualenv. Any ideas?

**Comment by richardleggett** [comment]
The instructions are a little different to what I had to do, it didn't prompt for the auth token, instead open up `uploader.py` and replace the string on line 25 where it assigns `access_token = "your_token"` with the token returned on the auth page in the previous step.

I encountered another problem after that however:

```
Connecting to Strava
No handlers could be found for logger "stravalib.model.Athlete"
Now authenticated for Richard Leggett
Uploading 2016-12-10-1121.gpx
Upload succeeded.
Waiting for response...
Another problem occured, sorry...
```

I added a log to the `except` to see what went wrong. Looks like the Exception is:

`local variable 'upload' referenced before assignment`

I don't know python but I'll have a stab now.

**Comment by richardleggett** [comment]
Alas more errors:

```Another problem occured: Could not find attribute `laps` on entity ``` I'll probably have to give up for the moment as I don't know enough python to fix this right now.

**Comment by tomwoolway** [comment]
@richardleggett if you're still having this problem, change the Stravalib in requirements.txt:

```
stravalib == 0.6.5
```

**Comment by barrald** [comment]
Should be fixed in latest, sorry for not getting to this for so long.
