### ISSUE TITLE
Uploading failing for activities manually added in Runkeeper

### ISSUE THREAD

**Issue by greatheights82** [barrald/strava-uploader#26]
Everything ran smoothly until the uploader got to the first row in my CVS without a GPX file because it was manually added in Runkeeper.

```
Traceback (most recent call last):
  File "../uploader.py", line 364, in <module>
    main()
  File "../uploader.py", line 352, in main
    if create_activity(client, activity_id, duration, distance, start_time, strava_activity_type, notes):
  File "../uploader.py", line 267, in create_activity
    upload = client.create_activity(
  File "/home/jhebert/.asdf/installs/python/3.8.6/lib/python3.8/site-packages/stravalib/client.py", line 585, in create_activity
    return model.Activity.deserialize(raw_activity, bind_client=self)
  File "/home/jhebert/.asdf/installs/python/3.8.6/lib/python3.8/site-packages/stravalib/model.py", line 130, in deserialize
    o.from_dict(v)
  File "/home/jhebert/.asdf/installs/python/3.8.6/lib/python3.8/site-packages/stravalib/model.py", line 63, in from_dict
    setattr(self, k, v)
  File "/home/jhebert/.asdf/installs/python/3.8.6/lib/python3.8/site-packages/stravalib/attributes.py", line 57, in __set__
    self.data[obj] = self.unmarshal(val)
  File "/home/jhebert/.asdf/installs/python/3.8.6/lib/python3.8/site-packages/stravalib/attributes.py", line 184, in unmarshal
    v = LatLon(lat=v[0], lon=v[1])
IndexError: list index out of range
```

**Comment by dannytranlx** [comment]
I just ran into the same issue. What I did was every time I ran into that error (I had 3 or 4 or those), I edited the CSV to remove that specific row (you can find which date in the logs) and it will be able to complete the import in the end. Somehow, the "Manual" activities were still imported before throwing the error, so nothing is lost just a little annoying.

**Comment by dannytranlx** [comment]
If someone wants to look into it, I pinpointed it down to those lines:
https://github.com/barrald/strava-uploader/blob/7beb18653d3f4f2a2f1467c3efcb4cb7f7f8ecd9/uploader.py#L245-L247

For some reason, it doesn't want to iterate through the `activities`. Maybe Strava changed their API and `stravalib 0.10.2` isn't compatible anymore?

**Comment by dannytranlx** [comment]
That's it, if you bump the `stravalib` to `0.10.4` in the `requirements.txt` and `pip install -r requirements.txt` again, it goes through without problem 🎉

**Comment by barrald** [comment]
Just merged the PR, thanks for submitting!
